Bump python version support to 3.11 and 3.12 - closes #107
jazzband/django-redshift-backend pull request #140
Opened 2024-07-24 20:01 UTC by fizyk

Subject: Add python 3.11 and 3.12 to test runs
Update pyproject.toml with 3.11 and 3.12 trove classifier

### Feature

- Feature

### Purpose
TO have pypi display django-redshift-backend as python 3.11 and python 3.12 compatible

### Detail
- Chore as everything worked

### Relates
- #107

2024-07-26 23:50 UTC, shimizukawa requested changes
The change looks good, but please remove the `.idea` directory.
Please remove `.idea` directory.

2024-07-26 23:50 UTC, shimizukawa commented on .idea/.gitignore
Please remove `.idea` directory.

2024-07-27 08:44 UTC, fizyk commented on .idea/.gitignore
Sorry about that.

2024-07-27 10:06 UTC, shimizukawa commented on .idea/.gitignore
Thanks!

2024-07-27 10:08 UTC, merged